### ISSUE TITLE
Da Angular5 a PWA

### ISSUE THREAD

**Issue by kasuken** [milano-js/good-party-2018#3]
Live coding per trasformare un'applicazione sviluppata con Angular 5 in una Progressive Web App.
10 minuti ci basteranno?
Ovvio, con spazio pure per le domande. 😀

**Comment by MaxArt2501** [comment]
Si spera che per maggio sia uscito Angular 6 🤞

**Comment by kasuken** [comment]
la sessione cambia di poco... 😵

**Comment by Granze** [comment]
@kasuken , chiudo questa issue visto che l'altra tua è più votata. Evitiamo anche di fare due talk quasi simili. ;)
